#!/bin/bash

# SLO Integration Example Script
# Demonstrates how to integrate SLO tracking into the Insurance Lead Gen platform

echo "=== Insurance Lead Gen SLO Integration Example ==="
echo ""

# Check if running in project directory
if [ ! -f "package.json" ]; then
    echo "Error: This script must be run from the project root directory"
    exit 1
fi

echo "1. Initializing SLO Management System"
echo "   - Setting up SLO definitions"
echo "   - Configuring error budget tracking"
echo "   - Registering Prometheus metrics"
echo ""

# Example: Initialize SLOs in API service
echo "2. API Service SLO Integration"
echo ""
echo "// apps/api/src/app.ts"
echo "import { initializeSLOs, MetricsCollector } from '@insurance-lead-gen/core';"
echo ""
echo "const app = express();"
echo "const metrics = new MetricsCollector('api-service');"
echo ""
echo "// Initialize SLOs on startup"
echo "initializeSLOs();"
echo ""
echo "// Use metrics middleware (automatically updates SLOs)"
echo "app.use(metrics.middleware());"
echo ""

echo "3. Orchestrator Service SLO Integration"
echo ""
echo "// apps/orchestrator/src/lead-processor.ts"
echo "import { LeadMetrics, updateSLOMetrics } from '@insurance-lead-gen/core';"
echo ""
echo "const leadMetrics = new LeadMetrics(registry, 'orchestrator');"
echo ""
echo "async function processLead(lead: Lead) {"
echo "  const start = Date.now();"
echo "  try {"
echo "    // Process lead..."
echo "    const result = await leadProcessingPipeline(lead);"
echo "    "
echo "    // Record success metrics"
echo "    leadMetrics.recordLeadProcessed('success', lead.source, 'orchestrator');"
echo "    leadMetrics.recordProcessingDuration('success', 'orchestrator', (Date.now() - start) / 1000);"
echo "    "
echo "    // This automatically updates SLO metrics:"
echo "    // - lead_processing_success_rate"
echo "    // - orchestrator_latency_p95"
echo "    "
echo "    return result;"
echo "  } catch (error) {"
echo "    // Record failure metrics"
echo "    leadMetrics.recordLeadProcessed('failed', lead.source, 'orchestrator');"
echo "    leadMetrics.recordProcessingDuration('failed', 'orchestrator', (Date.now() - start) / 1000);"
echo "    "
echo "    // This automatically updates SLO metrics with failure"
echo "    "
echo "    throw error;"
echo "  }"
echo "}"
echo ""

echo "4. AI Service SLO Integration"
echo ""
echo "// apps/backend/src/ai-service.ts"
echo "import { AIMetrics } from '@insurance-lead-gen/core';"
echo ""
echo "const aiMetrics = new AIMetrics(registry, 'ai-service');"
echo ""
echo "async function scoreLeadWithAI(lead: Lead) {"
echo "  const start = Date.now();"
echo "  try {"
echo "    // Call AI model..."
echo "    const score = await aiModel.predict(lead);"
echo "    "
echo "    // Record AI metrics"
echo "    aiMetrics.recordModelCall('lead-scoring-v2', 'success', 'ai-service');"
echo "    aiMetrics.recordModelLatency('lead-scoring-v2', 'ai-service', (Date.now() - start) / 1000);"
echo "    "
echo "    // This automatically updates SLO metrics:"
echo "    // - ai_model_success_rate"
echo "    // - ai_model_latency_p95"
echo "    "
echo "    return score;"
echo "  } catch (error) {"
echo "    // Record AI error metrics"
echo "    aiMetrics.recordModelCall('lead-scoring-v2', 'failed', 'ai-service');"
echo "    aiMetrics.recordModelError('lead-scoring-v2', error.type, 'ai-service');"
echo "    "
echo "    // This automatically updates SLO metrics with failure"
echo "    "
echo "    throw error;"
echo "  }"
echo "}"
echo ""

echo "5. Monitoring SLO Compliance"
echo ""
echo "# Access SLO dashboard"
echo "kubectl port-forward -n monitoring svc/grafana 3000:3000"
echo "# Open http://localhost:3000/d/slo-tracking"
echo ""
echo "# Query SLO metrics directly"
echo "curl http://localhost:9090/api/v1/query?query=slo_availability_percentage"
echo ""
echo "# Check error budget status"
echo "curl http://localhost:9090/api/v1/query?query=slo_error_budget_remaining"
echo ""

echo "6. SLO Alert Configuration"
echo ""
echo "# Alerts are pre-configured in monitoring/prometheus/alerts.yml"
echo "# Key SLO alerts:"
echo "# - SLOViolationCritical: < 95% availability"
echo "# - SLOViolationWarning: 95-99% availability"
echo "# - ErrorBudgetCritical: < 10% remaining"
echo "# - ErrorBudgetWarning: 10-30% remaining"
echo "# - HighErrorBudgetBurnRate: > 1.5x normal rate"
echo ""

echo "7. Error Budget Management"
echo ""
echo "# Check error budget status programmatically"
echo "const errorBudget = getErrorBudgetStatus('api_availability', 'api-service');"
echo "console.log('Remaining budget:', errorBudget.remainingBudget, 'minutes');"
echo "console.log('Burn rate:', errorBudget.burnRate, 'minutes/hour');"
echo ""
echo "# Calculate time to exhaustion"
echo "const timeToExhaustion = calculateTimeToExhaustion('api_availability', 'api-service');"
echo "console.log('Time to exhaustion:', timeToExhaustion, 'minutes');"
echo ""

echo "8. SLO Reset Procedure"
echo ""
echo "# Reset error budgets at start of new SLO window"
echo "# Typically run via cron job at midnight on day 1 of new window"
echo "resetErrorBudgets();"
echo ""

echo "9. Runbook Integration"
echo ""
echo "# SLO-related runbooks are available in docs/RUNBOOKS.md"
echo "# Key runbooks:"
echo "# - SLO Violation Response"
echo "# - Error Budget Depletion"
echo "# - High Error Budget Burn Rate"
echo "# - SLO Reset Procedure"
echo ""

echo "10. Post-Incident Review Integration"
echo ""
echo "# After SLO violations, create PIRs to document learnings"
echo "./scripts/create-pir.sh \\
  --incident-id INC-2023-001 \\
  --title \"SLO Violation - API Service\" \\
  --root-cause \"Database connection pool exhaustion\" \\
  --action-items \"Increase connection pool size,Add monitoring\""
echo ""

echo "=== SLO Integration Complete ==="
echo ""
echo "Key Benefits:"
echo "✅ Automatic SLO tracking across all services"
echo "✅ Real-time error budget monitoring"
echo "✅ Integrated alerting with runbook links"
echo "✅ Comprehensive dashboards for visibility"
echo "✅ Post-incident learning and improvement"
echo "✅ Data-driven reliability management"
echo ""
echo "Next Steps:"
echo "1. Review SLO definitions in packages/core/src/monitoring/slos.ts"
echo "2. Customize SLO targets for your specific requirements"
echo "3. Set up error budget alerts in monitoring/prometheus/alerts.yml"
echo "4. Train teams on SLO-based decision making"
echo "5. Monitor and refine SLOs based on real-world performance"
